package analytics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// Business-level Prometheus metrics shared by the api, worker and scheduler.
var (
	postsIngestedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "pulsegraph_posts_ingested_total",
		Help: "Total posts ingested into the platform.",
	})
	sentimentProcessedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "pulsegraph_sentiment_processed_total",
		Help: "Total posts scored by the sentiment engine.",
	})
	embeddingsGeneratedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "pulsegraph_embeddings_generated_total",
		Help: "Total post embeddings generated and stored.",
	})
	pipelineFailuresTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "pulsegraph_pipeline_failures_total",
		Help: "Pipeline stage failures by stage.",
	}, []string{"stage"})
	analyticsRunsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "pulsegraph_analytics_runs_total",
		Help: "Scheduled analytics recomputation runs by kind.",
	}, []string{"kind"})
	reportsGeneratedTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "pulsegraph_reports_generated_total",
		Help: "AI reports generated by mode (template or ml-service).",
	}, []string{"mode"})
)

// IncPostsIngested records one ingested post.
func IncPostsIngested() { postsIngestedTotal.Inc() }

// IncSentimentProcessed records one scored post.
func IncSentimentProcessed() { sentimentProcessedTotal.Inc() }

// IncEmbeddingGenerated records one stored embedding.
func IncEmbeddingGenerated() { embeddingsGeneratedTotal.Inc() }

// IncPipelineFailure records a stage failure.
func IncPipelineFailure(stage string) { pipelineFailuresTotal.WithLabelValues(stage).Inc() }

// IncAnalyticsRun records one scheduled analytics run ("trends", "graph",
// "demographics").
func IncAnalyticsRun(kind string) { analyticsRunsTotal.WithLabelValues(kind).Inc() }

// IncReportGenerated records one generated report by mode.
func IncReportGenerated(mode string) { reportsGeneratedTotal.WithLabelValues(mode).Inc() }
