FROM golang:1.25-alpine AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/scheduler ./cmd/scheduler

FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata && adduser -D -u 10001 pulsegraph
USER pulsegraph

COPY --from=build /out/scheduler /usr/local/bin/scheduler

EXPOSE 9092

ENTRYPOINT ["/usr/local/bin/scheduler"]
